api/src/app.ts
app/package.json

Fix admin app not returned from api

---

api/package-lock.json
api/package.json
package-lock.json
package.json

Makes sure you can run the API dev script on Windows as well as macOS

Use cross-env in api dev script

---

api/src/routes/items.ts
api/src/routes/users.ts
api/src/services/items.ts
app/src/stores/user/user.ts

Adds `/users/me/track/page` endpoint to update the `last_page` field without saving a revision for it

User track page

---

api/example.env
api/src/database/seeds/system.yaml
api/src/routes/files.ts
api/src/services/files.ts
api/src/types/files.ts

* Make sure to delete thumbnails on upload (replace)
* Delete thumbnails on delete file

Cleanup files service

---

api/src/services/collections.ts
api/src/services/fields.ts
api/src/services/items.ts

Default nullable to YES on field creation with nullable omitted

---

api/src/services/collections.ts

Cascade deletion of collection across activity / revisions / presets

---

app/src/modules/settings/routes/data-model/collections/components/new-collection/new-collection.vue

Use correct secondary style for cancel button

---

app/src/routes/login/components/continue-as/continue-as.vue
app/src/routes/login/login.vue

Return reactive authenticated flag on login

---

app/src/modules/settings/routes/data-model/field-detail/components/relationship-m2m.vue
app/src/modules/settings/routes/data-model/field-detail/components/relationship-m2o.vue
app/src/modules/settings/routes/data-model/field-detail/components/relationship-o2m.vue
app/src/modules/settings/routes/data-model/field-detail/field-detail.vue

Ensures you can edit just created relational fields properly
Fixes #51

Rehydrate relations on field creation

---

app/src/router.ts
app/src/routes/logout/index.ts
app/src/routes/logout/logout.vue

Ensures nothing is trying to read from the store while it's being emptied.
Fixes #38

Navigate to empty route before logging

---

app/src/app.vue
app/src/components/register.ts
app/src/components/transition/bounce/index.ts
app/src/components/transition/bounce/transition-bounce.vue
app/src/components/transition/dialog/index.ts
app/src/components/transition/dialog/transition-dialog.vue
app/src/components/v-dialog/v-dialog.vue
app/src/components/v-menu/v-menu.vue
app/src/modules/files/routes/add-new/add-new.vue
app/src/modules/settings/routes/data-model/field-detail/field-detail.vue
app/src/styles/lib/_portal-vue.scss
app/src/styles/main.scss

Rely on portal transitions for menu / dialog, increases rendering perf, makes sure enter animation fires on modal usage in portal for child route

Outlet transitions

---

app/src/modules/settings/routes/data-model/field-detail/store.ts

Fix o2m relational field setup

---

app/src/directives/tooltip/tooltip.ts

fix tooltip showing when element is deleted

---

app/src/directives/tooltip/tooltip.ts
app/src/views/private/components/drawer-detail/drawer-detail.vue
app/src/views/private/private-view.vue

Reposition, remove stop propagation to ensure drawer selects are closed
Fixes #39

Drawer close

---

app/.eslintrc.js
app/src/composables/use-item/use-item.ts
app/src/directives/tooltip/tooltip.ts
app/src/interfaces/many-to-one/many-to-one.vue
app/src/lang/en-US/index.json
app/src/modules/collections/composables/use-navigation.ts
app/src/modules/collections/routes/browse-or-detail/browse-or-detail.vue
app/src/modules/collections/routes/browse/browse.vue
app/src/modules/collections/routes/detail/detail.vue
app/src/modules/files/components/add-folder/add-folder.vue
app/src/modules/files/routes/browse/browse.vue
app/src/modules/files/routes/detail/detail.vue
app/src/modules/settings/routes/data-model/collections/collections.vue
app/src/modules/settings/routes/data-model/fields/fields.vue
app/src/modules/settings/routes/presets/browse/browse.vue
app/src/modules/settings/routes/presets/detail/detail.vue
app/src/modules/settings/routes/project/project.vue
app/src/modules/settings/routes/roles/browse/browse.vue
app/src/modules/settings/routes/roles/detail/detail.vue
app/src/modules/users/routes/browse/browse.vue
app/src/modules/users/routes/detail/detail.vue
app/src/stores/collections/collections.ts
app/src/stores/collections/types.ts
app/src/styles/_tooltip.scss
app/src/views/private/components/search-input/search-input.vue

Action button tooltips

---

api/src/database/run-ast.ts

If you had any other filters, it was using an OR for search query, instead of AND

Fix search

---

app/src/components/v-dialog/v-dialog.vue
app/src/components/v-field-template/v-field-template.vue
app/src/components/v-form/form-field.vue
app/src/components/v-input/v-input.story.ts
app/src/components/v-list/v-list-group.vue
app/src/components/v-list/v-list.vue
app/src/components/v-menu/readme.md
app/src/components/v-menu/use-popper.ts
app/src/components/v-menu/v-menu.vue
app/src/interfaces/file/file.vue
app/src/interfaces/icon/icon.vue
app/src/interfaces/many-to-one/many-to-one.vue
app/src/interfaces/status/status.vue
app/src/interfaces/user/user.vue
app/src/lang/en-US/index.json
app/src/modules/files/components/folder-picker/folder-picker-list-item.vue
app/src/modules/files/components/folder-picker/folder-picker.vue
app/src/modules/files/components/navigation/navigation-folder.vue
app/src/modules/files/composables/use-folders.ts
app/src/modules/settings/routes/data-model/collections/components/collection-options/collection-options.vue
app/src/modules/settings/routes/data-model/fields/components/field-select/field-select.vue
app/src/modules/settings/routes/data-model/fields/components/fields-management/fields-management.vue
app/src/views/private/components/comments-drawer-detail/comment-item-header.vue
app/src/views/private/components/filter-drawer-detail/field-filter.vue
app/src/views/private/components/filter-drawer-detail/filter-drawer-detail.vue
app/src/views/private/components/image-editor/image-editor.vue
app/src/views/private/components/revisions-drawer-detail/revisions-modal-picker.vue

Folders ctx

---

app/src/interfaces/index.ts
app/src/interfaces/markdown/demo.md
app/src/interfaces/markdown/index.ts
app/src/interfaces/markdown/markdown.story.ts
app/src/interfaces/markdown/markdown.test.ts
app/src/interfaces/markdown/markdown.vue
app/src/interfaces/markdown/readme.md
app/src/lang/en-US/index.json

Add markdown interface

---

api/src/controllers/items.ts
api/src/database/seeds/system.yaml
app/src/composables/use-collection/use-collection.ts
app/src/layouts/tabular/tabular.vue
app/src/modules/settings/routes/data-model/new-collection/new-collection.vue
app/src/types/collections.ts

Manage the sort field per collection on the collection level, instead of relying on a special flag

Sort field setup

---

app/src/interfaces/one-to-many/index.ts
app/src/lang/en-US/index.json
app/src/modules/settings/routes/data-model/field-detail/components/interface.vue
app/src/modules/settings/routes/data-model/field-detail/field-detail.vue
app/src/modules/settings/routes/data-model/field-detail/store.ts
app/src/modules/settings/routes/data-model/fields/components/fields-management/fields-management.vue

Closes https://github.com/directus/next/issues/143

Add presentation type fields in field setup flow

---

api/src/exceptions/base.ts
api/src/exceptions/index.ts
api/src/exceptions/invalid-otp.ts
api/src/middleware/error-handler.ts
api/src/services/authentication.ts

Use updated errors output format

---

api/src/database/seeds/system.yaml
api/src/services/authorization.ts
api/src/services/collections.ts
api/src/services/items.ts
api/src/services/payload.ts
api/src/services/utils.ts
api/src/types/permissions.ts
api/src/types/services.ts
api/src/utils/generate-joi.ts
api/src/utils/get-ast-from-query.ts
app/src/interfaces/code/code.vue
app/src/lang/en-US/index.json
app/src/modules/settings/index.ts
app/src/modules/settings/routes/roles/detail/components/permissions-overview/index.ts
app/src/modules/settings/routes/roles/detail/components/permissions-overview/permissions-overview-header.vue
app/src/modules/settings/routes/roles/detail/components/permissions-overview/permissions-overview-row.vue
app/src/modules/settings/routes/roles/detail/components/permissions-overview/permissions-overview-toggle.vue
app/src/modules/settings/routes/roles/detail/components/permissions-overview/permissions-overview.vue
app/src/modules/settings/routes/roles/detail/detail.vue
app/src/modules/settings/routes/roles/index.ts
app/src/modules/settings/routes/roles/permissions-detail/components/actions.vue
app/src/modules/settings/routes/roles/permissions-detail/components/fields.vue
app/src/modules/settings/routes/roles/permissions-detail/components/permissions.vue
app/src/modules/settings/routes/roles/permissions-detail/components/presets.vue
app/src/modules/settings/routes/roles/permissions-detail/components/tabs.vue
app/src/modules/settings/routes/roles/permissions-detail/components/validation.vue
app/src/modules/settings/routes/roles/permissions-detail/index.ts
app/src/modules/settings/routes/roles/permissions-detail/permissions-detail.vue
app/src/types/index.ts
app/src/types/permissions.ts

Add permissions settings

---

app/src/displays/collection/index.ts
app/src/displays/datetime/index.ts
app/src/displays/formatted-value/index.ts
app/src/displays/icon/index.ts
app/src/displays/image/index.ts
app/src/displays/mime-type/index.ts
app/src/displays/rating/index.ts
app/src/displays/user/index.ts
app/src/interfaces/divider/index.ts
app/src/interfaces/markdown/index.ts
app/src/interfaces/tags/index.ts
app/src/lang/en-US/displays.json

Requires https://github.com/directus/next/pull/220

Added missing default values

---

api/src/services/fields.ts
api/src/services/payload.ts
api/src/types/field.ts
api/src/utils/get-local-type.ts

Add csv special type, return type based on special flag

---

app/src/components/v-detail/readme.md
app/src/components/v-detail/v-detail.vue
app/src/interfaces/checkboxes/checkboxes.vue
app/src/interfaces/checkboxes/index.ts
app/src/lang/en-US/interfaces.json

This image shows how I implemented this but I'm up for a discussion on how we want to toggle this!

Hide too many checkboxes

---

app/src/interfaces/repeater/repeater.vue

Now opens the repeater row when creating a new one.

fix repeater row not opening when created

---

app/src/displays/icon/index.ts
app/src/interfaces/checkboxes/index.ts
app/src/interfaces/dropdown-multiselect/index.ts
app/src/interfaces/icon/icon.vue
app/src/interfaces/tags/index.ts
app/src/modules/settings/routes/data-model/field-detail/components/interface.vue

Added CSV types.
Fixed alignment and icon of icon interface.

Add csv to interfaces fix icon alignment and icon

---

app/src/displays/boolean/boolean.vue
app/src/displays/boolean/index.ts
app/src/interfaces/toggle/index.ts
app/src/lang/en-US/displays.json

Add boolean display

---

app/src/displays/related-values/related-values.vue
app/src/interfaces/translations/index.ts
app/src/interfaces/translations/translations.vue
app/src/interfaces/types.ts
app/src/lang/en-US/index.json
app/src/modules/settings/routes/data-model/field-detail/components/languages.vue
app/src/modules/settings/routes/data-model/field-detail/components/schema.vue
app/src/modules/settings/routes/data-model/field-detail/components/translations.vue
app/src/modules/settings/routes/data-model/field-detail/field-detail.vue
app/src/modules/settings/routes/data-model/field-detail/store.ts
app/src/modules/settings/routes/data-model/fields/components/fields-management.vue

Update translations interface to work as m2m, add setup flow in settings, add auto-generation for translations/languages collections

Translations setup

---

app/.storybook/mock-data/collections.json
app/.storybook/mock-data/fields.json
app/src/composables/use-preset/types.ts
app/src/composables/use-preset/use-preset.ts
app/src/lang/en-US/index.json
app/src/modules/collections/routes/browse.vue
app/src/stores/presets.ts
app/src/types/presets.ts
app/src/views/private/components/export-drawer-detail/export-drawer-detail.vue
app/src/views/private/components/export-drawer-detail/index.ts

Add export drawer detail, fix search

---

api/src/database/seeds/system.yaml
api/src/services/roles.ts
app/src/modules/settings/routes/roles/add-new.vue
app/src/modules/settings/routes/roles/app-required-permissions.ts

+ Handle foreign key constraints in role deletion

Save app required permissions on role creation

---

api/.gitignore
api/src/controllers/extensions.ts
api/src/services/extensions.ts
app/src/displays/register.ts
app/src/hydrate.ts
app/src/interfaces/register.ts
app/src/layouts/index.ts
app/src/layouts/register.ts
app/src/main.ts
app/src/modules/register.ts
app/src/modules/settings/routes/presets/browse/browse.vue
app/src/modules/settings/routes/presets/detail.vue
app/src/views/private/components/layout-drawer-detail/layout-drawer-detail.vue

Pull in custom interfaces from the API

---

app/src/interfaces/tags/index.ts
app/src/interfaces/tags/tags.vue
app/src/lang/en-US/interfaces.json

Added case and space-replace prop to tags interface

---

api/package-lock.json
app/src/displays/boolean/boolean.vue
app/src/interfaces/color/index.ts
app/src/interfaces/repeater/options.vue
app/src/lang/en-US/displays.json

fixed boolean, color display and repeater options

---

app/src/interfaces/many-to-one/many-to-one.vue

Fall back to modal instead of dropdown if totalCount null

---

api/src/database/seeds/01-tables/01-collections.yaml

This will fix seed issues for sql server 
Closes https://github.com/directus/next/issues/364

amended collections def so field length is 64 chars

---

app/src/views/private/private-view.vue

Fixes #314
In theory this only hides the underlying issue. But investigating further seems to be a more complex task.

Fix drag handles not working on Windows

---

app/src/displays/labels/index.ts
app/src/interfaces/_system/interface/interface.vue
app/src/interfaces/checkboxes/index.ts
app/src/interfaces/color/index.ts
app/src/interfaces/dropdown-multiselect/index.ts
app/src/interfaces/dropdown/index.ts
app/src/interfaces/repeater/options.vue
app/src/lang/en-US/displays.json
app/src/lang/en-US/interfaces.json

closes #392
I have to check if saving works which I currently could not do because the api threw a lot of error 500s at me.

Tweaked label display and a few translations

---

api/src/database/seeds/01-tables/03-users.yaml
api/src/middleware/authenticate.ts

Rename last_login to last_access, track on api use

---

app/src/components/v-upload/v-upload.vue
app/src/interfaces/file/file.vue
app/src/interfaces/files/files.vue
app/src/interfaces/image/image.vue
app/src/modules/files/routes/add-new.vue

Add missing chooseFromLib and loadFromUrl options in modal

---

api/src/database/run-ast.ts
api/src/utils/apply-query.ts

Adds support for filtering top level items based on a nested filter. 
Uses left joins to pull in the filterable value and processes the regular filter operator on this nested key to filter the parent level items.
Fixes #176

Add support for dot notation in filter parameter

---

api/src/services/fields.ts
app/src/components/v-list/v-list-item.vue
app/src/interfaces/translations/translations.vue
app/src/lang/en-US/index.json
app/src/modules/settings/routes/data-model/field-detail/components/translations.vue
app/src/modules/settings/routes/data-model/field-detail/field-detail.vue
app/src/modules/settings/routes/data-model/field-detail/store.ts
app/src/modules/settings/routes/data-model/fields/components/field-select.vue
app/src/modules/settings/routes/data-model/fields/components/fields-management.vue
app/src/modules/settings/routes/data-model/fields/fields.vue
app/src/modules/settings/routes/data-model/get-local-type.ts

- Combine translations/languages pane
- Generate languages on auto generate of languages collection
- Add translations setup quickstart
- Show translations as group on field management
- Tweak spacing
Closes #410, closes #347

Translation updates

---

api/src/exceptions/failed-validation.ts
api/src/services/authorization.ts
api/src/services/items.ts
api/src/utils/generate-joi.ts
api/src/utils/test.ts
app/src/components/v-form/form-field-label.vue
app/src/lang/en-US/index.json

Instead of erroring out vaguely, it will show the validation state for required as well:
(note, red project logo is my custom setting)

Surface required in app

---

api/src/cli/commands/start.ts

I'm not sure if this is the proper way of doing this or if I missed something, but this should avoid the process being trapped due to something stuck in the event loop.

Added process.exit and database connection shutdown

---

.github/actions/build-images/rootfs/usr/bin/entrypoint
.github/workflows/build-images.yml

Needs to add `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD` secrets to repository settings.

Added push to docker hub

---

app/src/modules/docs/components/sections.ts
app/src/modules/docs/index.ts
app/src/modules/docs/routes/docs.vue

Add defaultSection and change title shown

---

.github/actions/build-images/rootfs/directus/images/main/rootfs/usr/bin/entrypoint

Removes a log leak from the database install command.
Fixes #491

Fix database install log leaking

---

.github/actions/build-images/action.yml
.github/workflows/build-images.yml

Fixes pushing images to docker hub

Fix registry address for DockerHub

---

app/src/components/v-select/v-select.vue
app/src/views/private/components/layout-drawer-detail/layout-drawer-detail.vue

Show icons in layout select

---

api/src/services/payload.ts
app/src/composables/use-field-tree/use-field-tree.ts
app/src/layouts/tabular/tabular.vue
app/src/modules/settings/routes/data-model/field-detail/store.ts

Add no-data special key to hide non-data fields in system

---

app/src/lang/en-US/index.json
app/src/modules/users/components/user-info-drawer-detail.vue
app/src/modules/users/routes/detail.vue

Move last access to user detail sidebar

---

app/src/components/v-form/v-form.vue

Fixes field being readonly when creating a new one.

---

app/src/modules/collections/routes/detail.vue
app/src/modules/files/routes/detail.vue
app/src/modules/settings/routes/data-model/fields/fields.vue
app/src/modules/users/routes/detail.vue

Fix back button opening modal

---

app/src/interfaces/repeater/repeater.vue

Add fallback template when none is set

---

app/public/index.html
app/src/app.vue

This will show a placeholder with `Loading...` until the project name becomes available.
Should also update between project changes.
closes #427

Change page title to project name (#427)

---

app/src/interfaces/color/color.vue

Add border on low contrast to color interface

---

app/src/modules/settings/routes/data-model/collections/components/collection-options.vue
app/src/modules/settings/routes/data-model/fields/components/field-select.vue

Change color of button when deleting field and collection

---

app/src/modules/docs/routes/markdown.vue

Fix code highlighting in docs

---

app/src/interfaces/_system/interface/interface.vue
app/src/interfaces/repeater/options.vue
app/src/lang/en-US/index.json
app/src/modules/settings/routes/data-model/field-detail/components/schema.vue

Add type field to repeater

---

app/src/lang/en-US/index.json
app/src/modules/settings/routes/data-model/new-collection.vue

Disable field when unselected in collection creation

---

app/src/modules/docs/routes/static.vue

fix view possibly being null

---

api/src/services/items.ts
api/src/services/payload.ts

- Add updateByQuery / deleteByQuery support
- Add upsert method
- Tweak IO of o2m

one to many

---

app/src/composables/use-shortcut/use-shortcut.ts

Fix keyCombination validation

---

app/src/modules/docs/components/navigation.vue
app/src/modules/docs/index.ts
docs/build.js

The navigation would fail to render because the `.bin` directory made it into folders.
It also would fail if props.path was null.

Fix docs navigation

---

api/src/env.ts

convert numeric values to number
Closes https://github.com/directus/next/issues/363

Convert Numeric Values of Environment Variables to Number

---

api/src/database/seeds/01-tables/13-settings.yaml
api/src/database/seeds/02-rows/02-permissions.yaml
api/src/database/seeds/03-fields/09-settings.yaml
app/package-lock.json
app/package.json
app/public/index.html
app/src/app.vue
app/src/interfaces/code/code.vue

- Add custom css field to settings
- Remove csslint
- Add custom-css support to app
Closes #561

Add custom css support

---

api/src/exceptions/index.ts
api/src/exceptions/unprocessable-entity.ts
api/src/services/roles.ts
api/src/services/users.ts

- Add unprocessable entity exception
- Add check making sure you have at least one admin role left before deletion
- Add last admin user check
Closes #509

delete last admin

---

app/src/components/v-item-group/v-item.vue
app/src/composables/groupable/groupable.ts
app/src/interfaces/repeater/repeater-row.vue
app/src/interfaces/repeater/repeater.vue

Fix opening repeater row when creating new one

---

app/src/main.ts
app/src/modules/files/routes/collection.vue
app/src/utils/upload-file/upload-file.ts
app/src/utils/upload-files/upload-files.ts
app/src/views/private/private-view.vue

Scope global file upload to file library

---

app/src/interfaces/icon/icon.vue

Add deselect option to icon interface

---

app/src/interfaces/code/index.ts

Organize code interface choices

---

app/src/displays/related-values/index.ts
app/src/displays/related-values/options.vue
app/src/displays/types.ts
app/src/modules/settings/routes/data-model/field-detail/components/display.vue
app/src/modules/settings/routes/data-model/field-detail/store.ts
app/src/types/fields.ts

Added v-field-template in options so you don't have to be scared of typing something in the template.
Only show display on relational setups.
closes #648

Improve related values display

---

api/package.json
api/src/services/fields.ts
api/src/services/payload.ts
api/src/utils/get-default-value.ts
api/src/utils/get-local-type.ts
app/src/lang/en-US/index.json
app/src/modules/settings/routes/data-model/field-detail/components/field.vue
app/src/modules/settings/routes/data-model/field-detail/components/schema.vue
app/src/modules/settings/routes/data-model/field-detail/field-detail.vue
app/src/modules/settings/routes/data-model/field-detail/store.ts

- Update schema inspector
- Add precision / scale support
Fixes #560

Add precision / scale support

---

app/package-lock.json
app/src/modules/settings/routes/data-model/fields/components/field-select.vue
package-lock.json

Hide duplicate on relational fields

---

api/src/utils/parse-filter.ts
app/src/interfaces/translations/translations.vue
app/src/views/private/components/drawer-item/drawer-item.vue

Use new drawer item detail, fix item loading, clean up staging of edits
- Start on new translations interface
- Fetch / render languages
- Finish translations

Cleanup translations interface

---

app/src/components/v-input/v-input.vue

Fix dbsafe prop of v-input component

---

app/package-lock.json
app/src/views/private/components/filter-sidebar-detail/filter-sidebar-detail.vue
app/src/views/private/components/filter-sidebar-detail/get-available-operators-for-type.ts

Add proper defaults for filters

---

app/src/modules/settings/routes/data-model/fields/components/field-select.vue

Add required indicator to field select

---

api/src/controllers/permissions.ts
api/src/controllers/users.ts
app/src/app.vue
app/src/hydrate.ts
app/src/views/private/private-view.vue

- Don't attempt loading app data for non-role users
- Fix colors on no-app-access warning
- Don't require user to have role in permissions/me
- Return user id as minimum data in /users/me
- Move no-app-access check to private views only
Fixes #714

Fix login in with user with no role

---

app/src/interfaces/wysiwyg/tinymce-overrides.css

closes #681
Here are some examples.

Clean up wysiwyg interface style

---

app/src/modules/activity/components/navigation.vue
app/src/modules/files/components/navigation.vue
app/src/views/private/components/revisions-drawer-detail/revisions-drawer-detail.vue
app/src/views/private/components/sidebar-detail/sidebar-detail.vue
docs/nav-app.yaml

1. Fix badge colors for comments
2. Changed My Files icon
3. Changed Getting Start icon

Small UX touches

---

api/src/database/seeds/02-rows/03-presets.yaml
app/src/displays/user/index.ts
app/src/displays/user/user.vue
app/src/interfaces/user/user.vue
app/src/lang/en-US/index.json
app/src/modules/activity/routes/item.vue
app/src/modules/files/components/file-info-sidebar-detail.vue
app/src/modules/settings/routes/data-model/fields/components/field-select.vue
app/src/modules/settings/routes/data-model/new-collection.vue
app/src/modules/settings/routes/presets/collection/collection.vue
app/src/modules/settings/routes/presets/item.vue
app/src/modules/users/routes/item.vue
app/src/routes/login/components/continue-as/continue-as.vue
app/src/stores/user.ts
app/src/utils/user-name.ts
app/src/views/private/components/comments-sidebar-detail/comment-item-header.vue
app/src/views/private/components/comments-sidebar-detail/comments-sidebar-detail.vue
app/src/views/private/components/comments-sidebar-detail/types.ts
app/src/views/private/components/revisions-drawer-detail/revision-item.vue
app/src/views/private/components/revisions-drawer-detail/revisions-drawer-detail.vue
app/src/views/private/components/revisions-drawer-detail/revisions-drawer-picker.vue
app/src/views/private/components/revisions-drawer-detail/types.ts
app/src/views/private/components/user-popover/user-popover.vue

- Add userName util function to render user's name
- Fix spacing of required star
- Fix user display not showing email
Fixes #715

Show email if user name isn't set

---

app/src/interfaces/many-to-many/use-relation.ts

Allow for relation to the same collection

---

app/src/modules/collections/routes/item.vue

Handle case where collectionInfo.meta is null

---

app/src/displays/datetime/datetime.vue
app/src/displays/datetime/index.ts
app/src/lang/en-US/displays.json
app/src/lang/en-US/index.json

closes #211 
It is now possible to choose between `Long`, `Short` and `Other` on the datetime display.

Allow for custom formats

---

app/src/modules/settings/routes/data-model/fields/components/field-select.vue

Fix cloning of a field

---

api/src/database/seeds/01-tables/07-files.yaml

Seeing there wasn't a problem with the uploaded_on field, this should theoretically fix 716. That being said, I'm not able to reproduce it on my end still, so it's a bit of a gamble.
﻿Fixes #716

Set default value for modified on column

---

app/src/interfaces/repeater/options.vue
app/src/interfaces/repeater/repeater-row.vue
app/src/interfaces/repeater/repeater.vue

Added name option
fixed last row being open on load
closes #744 closes #743

Fix repeater open on load and add name option

---

app/src/components/v-field-template/v-field-template.vue
app/src/interfaces/tags/tags.vue
app/src/modules/docs/components/markdown.vue
app/src/modules/docs/index.ts

Replace `replaceAll` with `replace`

---

app/src/interfaces/many-to-many/use-preview.ts

Fix nested information not loading

---

app/src/utils/upload-file/upload-file.ts

Uploading files give error cause file not uploaded.

Fix file upload

---

app/package-lock.json
app/src/interfaces/wysiwyg/tinymce-overrides.css
package-lock.json

Fix some visual glitches in wysiwyg editor
Also input fields border color, buttons inconsistency

Tune the tox style to match better directus themes

---

app/src/interfaces/file/index.ts
app/src/interfaces/files/index.ts
app/src/interfaces/image/index.ts
app/src/interfaces/many-to-many/index.ts
app/src/interfaces/many-to-one/index.ts
app/src/interfaces/one-to-many/index.ts
app/src/interfaces/types.ts
app/src/modules/settings/routes/data-model/field-detail/store.ts

Add localType to interfaces

---

app/src/views/private/components/drawer-collection/drawer-collection.vue

- Add search input to collections drawer
- Pass search query to layout
Closes #779

Add search input to collections drawer

---

app/src/interfaces/code/code.vue

Maybe the code interface needs some clean up in the future to fix this in a more clean way.
Feel free to test @goggi.
Fixes #800

Only emit actual user input in code interface

---

api/src/mail/index.ts
api/src/mail/templates/base.liquid
api/src/mail/templates/password-reset.liquid
api/src/mail/templates/user-invitation.liquid

Use project name, color & logo inside the mail template.

Cleanup & white-label the email templates

---

api/src/utils/apply-query.ts

Fix _ncontains typo

---

.github/actions/build-images/rootfs/directus/images/main/examples/docker-compose.yml
.github/actions/build-images/rootfs/directus/images/main/rootfs/usr/bin/entrypoint

Wait for database on bootstrap

---

app/src/components/v-form/form-field.vue

This feature was in v8 as well.

Only enable save options if a value has changed

---

api/src/database/migrations/20201105A-add-cascade-system-relations.ts
api/src/database/migrations/run.ts
api/src/services/users.ts

Update system key constraints

---

api/src/controllers/collections.ts
api/src/controllers/files.ts
api/src/controllers/folders.ts
api/src/controllers/items.ts
api/src/controllers/permissions.ts
api/src/controllers/presets.ts
api/src/controllers/relations.ts
api/src/controllers/roles.ts
api/src/controllers/users.ts
api/src/controllers/webhooks.ts
app/src/components/v-form/v-form.vue
app/src/modules/collections/routes/collection.vue
app/src/modules/collections/routes/item.vue
app/src/views/private/components/drawer-batch/drawer-batch.vue
app/src/views/private/components/drawer-batch/index.ts

- Start on new batch operations
- Add batch delete w/ keys in body
- Update batch style to drawer
- Update batch archive to use new update flow
Fixes #819

Extend batch delete / update

---

api/src/services/assets.ts
app/src/api.ts
app/src/displays/file/file.vue
app/src/displays/image/image.vue
app/src/displays/user/user.vue
app/src/interfaces/file/file.vue
app/src/interfaces/image/image.vue
app/src/layouts/cards/components/card.vue
app/src/modules/users/routes/item.vue
app/src/views/private/components/comments-sidebar-detail/comment-item-header.vue
app/src/views/private/components/image-editor/image-editor.vue
app/src/views/private/components/module-bar-avatar/module-bar-avatar.vue
app/src/views/private/components/module-bar-logo/module-bar-logo.vue
app/src/views/private/components/user-popover/user-popover.vue

Add permissions to /assets endpoint
