app/src/modules/collections/routes/overview/overview.vue, app/src/modules/settings/index.ts, app/src/modules/settings/routes/data-model/collections/collections.vue, app/src/modules/settings/routes/data-model/collections/components/new-collection/index.ts, app/src/modules/settings/routes/data-model/fields/components/fields-management/fields-management.vue, app/src/modules/settings/routes/data-model/index.ts, app/src/modules/settings/routes/data-model/new-collection/index.ts, app/src/modules/settings/routes/data-model/new-collection/new-collection.vue
Renders the new collection modal as a sub-route of `/settings/data-model` (under `/settings/data-model/+`). This ensures that it's reinitialized fresh every time, and allows us to deep link to it from the "No collections available yet" warning 
Fixes #47
=> Change collection setup to childroute

app/src/components/v-tabs/readme.md
I need to add the v-model to v-tabs-items as well, is this correct? It does not work without it.
=> add v-model to tab-items

app/src/interfaces/datetime/datetime.vue
Fixes https://github.com/directus/next/issues/232
Had to check if the dates match cause the iso format was formatted as a different string which still was correct iso.
=> fix datetime emiting without changes

app/src/components/v-overlay/v-overlay.vue
Fixes https://github.com/directus/next/issues/228
I'm not sure if we want to render every overlay in front of a dropdwon but I could not think of a situation where we would have this case.
=> fix dropdown rendering before overly

api/src/services/collections.ts, app/src/auth.ts, app/src/lang/en-US/index.json, app/src/modules/settings/routes/data-model/field-detail/components/relationship-m2m.vue, app/src/modules/settings/routes/data-model/field-detail/components/relationship-m2o.vue, app/src/modules/settings/routes/data-model/field-detail/components/relationship-o2m.vue, app/src/modules/settings/routes/data-model/field-detail/field-detail.vue, app/src/modules/settings/routes/data-model/field-detail/store.ts, app/src/modules/settings/routes/data-model/new-collection.vue
=> Relational setup tweaks

api/src/database/run-ast.ts, api/src/middleware/sanitize-query.ts, api/src/types/query.ts, api/src/utils/get-ast-from-query.ts
Closes #178 
Allows you to apply any of the query params to a nested subset of data, like setting a limit on nested o2m records:
```
GET /items/recipes
?fields=*.*.*
&limit=15                         << Fetch 15 recipes
&deep[ingredients][limit]=3       << Only fetch 3 ingredients per recipe
```
=> Add `deep` query param support

app/src/modules/files/routes/detail.vue
The folder got checked for undefined but was null so navigation didn't work.
=> Fix back arrow in folder

app/src/modules/settings/routes/presets/browse/components/presets-info-drawer-detail.vue
This fixes a RangeError and the drawer not showing the presets and
bookmarks count.
=> Fix presets filter query

app/src/modules/settings/routes/presets/browse/browse.vue
This fixes the presets and bookmarks browse view not showing any values
in the name column.
=> Fix presets bookmark field name

api/src/database/seeds/02-rows/04-relations.yaml
This fixes the presets and bookmarks browse view showing All instead of
the role if the scope is set to a role.
=> Add relation between presets and roles to seeds

api/src/database/run-ast.ts, api/src/utils/get-ast-from-query.ts
* Return PKs in nested collection nodes if no fields are selected.
* Include relational fields in wildcard conversion
=> Return pks in o2m

app/src/modules/settings/routes/data-model/field-detail/components/relationship-m2o.vue
When creating a m2o relation and adding a corresponding field, the field name didn't get set until you changed ending up in a relation that had no `one_field`.
=> Fix corresponding field name not getting set in store

api/src/utils/list-folders.ts
List folders assumes it's always a relative path, but since it can come from an environment variable it's possible to set it as an absolute path.
=> Fix absolute extension path support

api/src/extensions.ts, api/src/types/extensions.ts
This should allow compiled typescript extensions to be used when exporting the extension with `export default function` instead of forcing the usage of `module.exports = function`
=> Allows default exports to be used in extensions

api/src/middleware/sanitize-query.ts, api/src/utils/parse-filter.ts, api/src/utils/sanitize-query.ts, api/src/utils/validate-query.ts, app/src/utils/filters-to-query/filters-to-query.ts
- Validate the used query before running it
- Update advanced filter drawer detail to match filter query check
Validate the query parameters before running operations to the DB. Should prevent a lot of 500s where you accidentally try filtering by illegal values.
=> filter check

api/src/database/seeds/01-tables/03-users.yaml, api/src/database/seeds/02-rows/04-relations.yaml, api/src/utils/get-ast-from-query.ts, app/src/stores/settings.ts
- Default new users to active status
- Fix *.* not fetching correct current level fields
- Add missing relation seeds
- Don't fetch settings with nested fields
- Don't treat top level m2os as relational
Fixes #668
=> Fix permissions for related items

app/src/modules/docs/components/markdown.vue
Tables in docs doesn't look very readable especially in dark mode.
=> Fix tables in docs constrast UX

app/src/hydrate.ts
`setLanguage` wasn't correctly awaited when hydrating the app. This explains why the bug was so random, because it would show the incorrect translation only when it didn't resolve in time before the next promise :smile: 
Maybe adding an eslint check to await promises/handle promise result could prevent something like this in the future? (eg: `@typescript-eslint/no-floating-promises`)
close #692
=> Fix translation not set before initial load

app/src/views/private/components/comments-sidebar-detail/comment-item-header.vue
Not sure for the correct behavior but think the condition is not in place. It also trigger and error
After
=> Fix record comment display

app/src/components/v-form/form-field-menu.vue
The first two commits are just quality of life changes.
The third commit also prevents a server error when a toggle interface is cleared and submitted.
More specifically this is a "SQLITE_CONSTRAINT: NOT NULL constraint failed" error, but I think the clear option should not be shown in general for fields that are set to be required and have a default value.
=> Some form field menu improvements

api/src/services/items.ts, app/src/modules/settings/routes/roles/permissions-detail/permissions-detail.vue
- Throw forbidden exception on 404
- VS Code, why.
- Close permissions drawer if permissions row doesn't exist
Fixes #680
=> permissions 404

api/src/database/seeds/03-fields/09-settings.yaml, api/src/types/field.ts, app/src/modules/settings/routes/data-model/new-collection.vue, app/src/stores/fields.ts, app/src/types/fields.ts
@rijkvanzanten is the `FieldMeta.required` property still used anywhere? Otherwise, I think it can be removed here and in a few other places.
=> Remove outdated required field property

app/src/modules/collections/routes/item.vue
This fixes the Unsaved Changes dialog not showing up except for singleton collections.
=> Call navigation guard in item route component

api/src/services/items.ts
Adds ability for extension developer to specify type returned from ItemsService. This helps have better
intellisense and better type safety when developing.
I imported `Item` as `AnyItem` because that way code stays more readable.
And I had to specify types in some places because other services don't have generic types.
Now we can do:
```typescript
interface Post {
name: string;
id: number;
}
const posts = new ItemsService<Post>('posts');
await posts.update({invalidKey: 'value'}, 1); // It will show error in IDE
const firstPost = await posts.readByQuery({ filter: { id: 1 }, single: true }); // Returns Post
```
=> Add generics for ItemsService

api/src/database/run-ast.ts, api/src/services/meta.ts, api/src/utils/apply-query.ts
This fixes a regression introduced in #786.
When using a SQLite database, items could not be updated any more.
This is due to knex by default only allowing a single connection for SQLite databases and the item update operation using applyFilter inside a transaction which tries to use a different knex instance to connect to the database.
=> Pass knex instance to applyFilter

docs/reference/environment-variables.md
Adding a variation of `postgres` as the Directus accepts as `DB_CLIENT` `pg` and `postgres`
=> Updating environment variable documentation

api/index.js, api/package.json, api/src/app.ts, api/src/utils/track.ts, app/public/index.html, app/src/main.ts
Fixes #91
Also fix importing Directus into existing express project. The following now works as expected:
```js
const express = require('express');
const { createApp } = require('directus');
async function init() {
const directus = await createApp();
express()
.get('/', (req, res) => res.send('Hello, World!'))
.use('/directus', directus)
.listen(1122, () => console.log('Running'));
}
init();
```
=> Allow App to run under subpath

api/src/app.ts
Fixes #826 
- Instead of using the `PUBLIC_URL` for redirecting `/` -> `/admin/`, use a relative path. This will still allow Directus to run under a subpath.
- Make sure the correct asset URLs are provided if the PUBLIC_URL ends with or without a `/`
=> Fix inconsistent PUBLIC_URL (#826)

app/src/lang/nl-NL/index.json
This will fix this bug:
I know it doesn't fix all translations, but my users are confused about this particular translation
=> Fix incorrect translation for 'collections' for nl-NL

app/src/views/public/public-view.vue
Add small fixes to optimize mobile support and scale elements propertly without overlapping each other or the screen.
This tiny update helps to keep elements in place for very small (and strange) screen resolutions. Since it is that tiny, I did not discuss it before the PR. Hope that's ok.
=> Small CSS Update to public-view.vue for better mobile support

api/src/mail/templates/base.liquid
Screenshot was taken in GMail, so it should render correctly now
=> Use inline-block instead of inline-flex for GMail support

api/src/env.ts
Updating CORS_ENABLED to true by default as the documentation describes 
Reference: [directus/next] New comment on issue #871: CORS is not enabled by default
=> Updating CORS_ENABLED to true by default

api/src/services/meta.ts
Just a small thing I noticed while working on #795. This should prevent issues if `MetaService` is ever used inside a transaction.
=> Use knex instance property in MetaService class

app/src/utils/filters-to-query/filters-to-query.ts
This fixes using multiple filters with the same field.
@rijkvanzanten what's your opinion on only allowing a single root field on filters as using `_and` essentially does the same thing without the limitation of not being able to specify the same field name multiple times?
Also, I think the corresponding readme file is a bit out of date. Shall I update it?
=> Use _and operator when converting filters to query

app/src/modules/settings/routes/roles/item/components/permissions-overview-header.vue
This was in v8 and should help users to understand the meaning of those icons and their respective columns.
=> Add tooltips to the icons in permissions header

api/src/cli/commands/users/create.ts, api/src/cli/index.ts
With the latest release candidates, attempting to create a user results in the following error:
```
TypeError: Cannot read property 'overview' of undefined
at Command.<anonymous> (/app/node_modules/directus/dist/cli/commands/users/create.js:22:50)
at Generator.next (<anonymous>)
at /app/node_modules/directus/dist/cli/commands/users/create.js:8:71
at new Promise (<anonymous>)
at __awaiter (/app/node_modules/directus/dist/cli/commands/users/create.js:4:12)
at Command.usersCreate (/app/node_modules/directus/dist/cli/commands/users/create.js:13:12)
at Command.listener [as _actionHandler] (/app/node_modules/directus/node_modules/commander/index.js:426:31)
at Command._parseCommand (/app/node_modules/directus/node_modules/commander/index.js:1002:14)
at Command._dispatchSubcommand …
```
=> Fix database import for user create command
